/* Work your exercises here */







export {
  addTwoNumbers,
  randomNumber,
  Person,
  printNumbers,
  printDelayedMessage,
  canDrive,
  guessTheBigger,
  guessTypeNumber,
  findTheMaxNumber,
  guessOddOrEvenNumber,
  processNumber,
  calculator,
  waitAndGreet,
  processElements,
  processString,
  arrayNumbers1,
  arrayNumbers2,
  arrayNumbers3,
  addRestParameters,
  citizen,
  citizenPlusCity,
  rest,
  resultSpreadArgumentsToFunction,
  mergeObject,
  squareNumbersArray,
  evenNumbersArray,
  firstGreaterThan10,
  totalCalculated,
  calculateDoubleGreaterThan10NumbersAddition,
  everyGreaterThan10,
  someGreaterThan10,
  printNamesWithForEach,
  printNamesWithForOf,
  evenNumbers,
  printKeyValuePairs,
  printUntilFive,
  printNamesWithIndex,
  myFirstPromise,
  useMyFirstPromise,
  promiseWithReject,
  asyncAwaitFunction,
  tryCatchFunction,
  promise1,
  promise2,
  allPromises,
};
